import type { ProviderCredentialKind, ProviderSourceAccess } from '@gev/contracts';

const ALL_ENVIRONMENTS = ['development', 'staging', 'production'] as const;
const NO_SCOPES: readonly string[] = [];

interface BaseAccessOptions {
  domain: string;
  productId: string;
  productName: string;
  endpoint: string;
  format: string;
  coverage: string;
  timeSemantics: string;
  credentialKind: ProviderCredentialKind;
  setupUrl: string;
  scopes?: readonly string[];
  validation: string;
  approval: 'not_required' | 'record_required';
  termsUrl: string;
  attributionUrl: string;
  configuration: 'not_required' | 'required';
  configurationDescription: string;
  refreshSeconds: number;
  maxStaleSeconds: number;
  rate: string;
  budget: string;
  maxBytes: number;
  maxRecords: number | null;
  killSwitch: string;
  fallback: string;
  instructions: readonly string[];
  transport?: 'https' | 'download_pack';
}

function access(options: BaseAccessOptions): ProviderSourceAccess {
  return {
    domain: options.domain,
    evidence_reviewed_on: '2026-09-05',
    decision_rank: null,
    products: [
      {
        id: options.productId,
        name: options.productName,
        transport: options.transport ?? 'https',
        endpoints: [options.endpoint],
        formats: [options.format],
        coverage: options.coverage,
        time_semantics: options.timeSemantics,
      },
    ],
    credential: {
      kind: options.credentialKind,
      setup_url: options.setupUrl,
      required_scopes: [...(options.scopes ?? NO_SCOPES)],
      validation_method: options.validation,
    },
    approval: {
      owner: 'gev-data-licensing-owner',
      status: options.approval,
      terms_url: options.termsUrl,
      attribution_url: options.attributionUrl,
      allowed_live_environments: [...ALL_ENVIRONMENTS],
    },
    configuration: {
      status: options.configuration,
      description: options.configurationDescription,
    },
    operations: {
      refresh_seconds: options.refreshSeconds,
      fresh_cache_seconds: options.refreshSeconds,
      max_stale_seconds: options.maxStaleSeconds,
      upstream_rate_limit: options.rate,
      budget_policy: options.budget,
      timeout_ms: 10_000,
      max_response_bytes: options.maxBytes,
      max_records: options.maxRecords,
      max_concurrency: 2,
      kill_switch: options.killSwitch,
      kill_switch_owner: 'gev-platform-administrator',
      fallback: options.fallback,
    },
    setup_instructions: [...options.instructions],
  };
}

const BASE_PROVIDER_ACCESS: Readonly<Record<string, ProviderSourceAccess>> = {
  opensky: access({
    domain: 'aviation',
    productId: 'opensky-state-vectors',
    productName: 'OpenSky state vectors',
    endpoint: 'https://opensky-network.org/api/states/all',
    format: 'JSON state vectors',
    coverage: 'Global ADS-B coverage subject to receiver availability',
    timeSemantics: 'Source state-vector and position timestamps remain distinct from retrieval',
    credentialKind: 'oauth2_client_credentials',
    setupUrl: 'https://openskynetwork.github.io/opensky-api/rest.html',
    scopes: ['authenticated REST access'],
    validation: 'No credential validation surface exists in Phase 5; use seed mode',
    approval: 'record_required',
    termsUrl: 'https://opensky-network.org/about/terms-of-use',
    attributionUrl: 'https://opensky-network.org/',
    configuration: 'required',
    configurationDescription: 'Live access requires approved OAuth2 client configuration.',
    refreshSeconds: 5,
    maxStaleSeconds: 30,
    rate: 'Existing adapter and cost-governor request ceilings apply',
    budget: 'Authenticated, cached, rate-limited, and budget-governed live reads only',
    maxBytes: 5_242_880,
    maxRecords: 10_000,
    killSwitch: 'opensky.enabled governed flag',
    fallback: 'Use the lawful deterministic seed fixture or report unavailable',
    instructions: [
      'Review OpenSky authentication, rate, and intended-use terms.',
      'Keep seed mode active until credentials and use approval can be administered in Phase 7.',
    ],
  }),
  aisstream: access({
    domain: 'maritime',
    productId: 'aisstream-position-reports',
    productName: 'AIS vessel position reports',
    endpoint: 'https://stream.aisstream.io/v0/stream',
    format: 'WebSocket JSON',
    coverage: 'Global receiver-contributed AIS coverage',
    timeSemantics: 'Message and position timestamps remain distinct from retrieval',
    credentialKind: 'api_key',
    setupUrl: 'https://aisstream.io/documentation',
    validation: 'No credential validation surface exists in Phase 5; use seed mode',
    approval: 'record_required',
    termsUrl: 'https://aisstream.io/',
    attributionUrl: 'https://aisstream.io/',
    configuration: 'required',
    configurationDescription: 'Live use requires an API key and bounded subscription area.',
    refreshSeconds: 15,
    maxStaleSeconds: 60,
    rate: 'One bounded server-owned stream subscription',
    budget: 'Live subscription remains authenticated, rate-limited, and budget governed',
    maxBytes: 2_097_152,
    maxRecords: 10_000,
    killSwitch: 'No dedicated provider kill switch is registered',
    fallback: 'Use the lawful deterministic seed fixture or report unavailable',
    instructions: [
      'Review AISStream account, API, subscription-area, and redistribution requirements.',
      'Keep seed mode active until secure credential administration exists in Phase 7.',
    ],
  }),
  celestrak: access({
    domain: 'orbital',
    productId: 'celestrak-standard-gp',
    productName: 'CelesTrak standard GP JSON/OMM',
    endpoint: 'https://celestrak.org/NORAD/elements/gp.php',
    format: 'JSON OMM',
    coverage: 'Server-owned STATIONS, WEATHER, GPS-OPS, and GEO groups',
    timeSemantics: 'Element epoch, retrieval, propagation, and cache times remain distinct',
    credentialKind: 'none',
    setupUrl: 'https://celestrak.org/NORAD/documentation/gp-data-formats.php',
    validation: 'No API key; live access remains gated by recorded commercial-use confirmation',
    approval: 'record_required',
    termsUrl: 'https://celestrak.org/NORAD/documentation/gp-data-formats.php',
    attributionUrl: 'https://celestrak.org/',
    configuration: 'required',
    configurationDescription: 'Explicit live-access and terms gates are required.',
    refreshSeconds: 7_200,
    maxStaleSeconds: 86_400,
    rate: 'Fixed server-owned group requests with transient retry backoff',
    budget: 'Live requests require the existing rate and budget governor',
    maxBytes: 5_242_880,
    maxRecords: 1_000,
    killSwitch: 'GEV_SATELLITES_ENABLED',
    fallback: 'Use the GEV synthetic seed catalog; never present it as live',
    instructions: [
      'Review CelesTrak usage guidance and the satellite source policy.',
      'Obtain written commercial-use confirmation or formal owner acceptance before live use.',
    ],
  }),
  usgs: access({
    domain: 'seismic',
    productId: 'usgs-earthquake-feed',
    productName: 'USGS real-time earthquake feed',
    endpoint: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php',
    format: 'GeoJSON',
    coverage: 'Global reviewed and automatic earthquake events',
    timeSemantics: 'Event origin and update times remain distinct from retrieval',
    credentialKind: 'none',
    setupUrl: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/',
    validation: 'No credential required',
    approval: 'not_required',
    termsUrl: 'https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits',
    attributionUrl: 'https://earthquake.usgs.gov/',
    configuration: 'not_required',
    configurationDescription: 'No live credential configuration is documented.',
    refreshSeconds: 60,
    maxStaleSeconds: 300,
    rate: 'Poll no faster than the registered feed cadence',
    budget: 'Cache and cost governor still apply to live reads',
    maxBytes: 5_242_880,
    maxRecords: 10_000,
    killSwitch: 'No dedicated provider kill switch is registered',
    fallback: 'Use the lawful deterministic seed fixture or report unavailable',
    instructions: ['Review the USGS feed, source-credit, and freshness guidance before live use.'],
  }),
  'nasa-firms': access({
    domain: 'thermal',
    productId: 'firms-area-csv',
    productName: 'FIRMS area thermal anomalies',
    endpoint: 'https://firms.modaps.eosdis.nasa.gov/api/area/csv/',
    format: 'CSV',
    coverage: 'Selected MODIS and VIIRS products within bounded geography',
    timeSemantics: 'Satellite acquisition time remains distinct from retrieval',
    credentialKind: 'api_key',
    setupUrl: 'https://firms.modaps.eosdis.nasa.gov/api/map_key/',
    validation: 'No credential validation surface exists in Phase 5; use seed mode',
    approval: 'record_required',
    termsUrl: 'https://firms.modaps.eosdis.nasa.gov/content/terms-of-use',
    attributionUrl: 'https://firms.modaps.eosdis.nasa.gov/',
    configuration: 'required',
    configurationDescription: 'Live use requires a server-side MAP_KEY, product, and geography.',
    refreshSeconds: 300,
    maxStaleSeconds: 1_800,
    rate: 'FIRMS transaction limits and existing cache policy apply',
    budget: 'Every live transaction is authenticated, cached, rate limited, and budget governed',
    maxBytes: 5_242_880,
    maxRecords: 10_000,
    killSwitch: 'No dedicated provider kill switch is registered',
    fallback: 'Use the lawful deterministic seed fixture or report unavailable',
    instructions: [
      'Review FIRMS product, map-key, attribution, and transaction-budget requirements.',
      'Keep the MAP_KEY server-side; credential submission is deferred to Phase 7.',
    ],
  }),
  'dot-traffic': access({
    domain: 'traffic-cameras',
    productId: 'source-specific-camera-catalog',
    productName: 'Source-specific public traffic camera catalog',
    endpoint: 'https://data.transportation.gov/',
    format: 'Source-specific catalog',
    coverage: 'Configured state or municipal transportation catalog only',
    timeSemantics: 'Catalog, image capture, retrieval, and stream times remain distinct',
    credentialKind: 'source_specific',
    setupUrl: 'https://data.transportation.gov/',
    validation: 'Each agency source requires a separate allowlisted decision',
    approval: 'record_required',
    termsUrl: 'https://www.transportation.gov/data',
    attributionUrl: 'https://www.transportation.gov/',
    configuration: 'required',
    configurationDescription: 'A separately approved agency endpoint and attribution are required.',
    refreshSeconds: 10,
    maxStaleSeconds: 60,
    rate: 'Source-specific rate and cache policy is mandatory',
    budget: 'No live source is enabled without a reviewed source-specific budget',
    maxBytes: 5_242_880,
    maxRecords: 1_000,
    killSwitch: 'No dedicated provider kill switch is registered',
    fallback: 'Use the deterministic seed catalog or report unavailable',
    instructions: ['Select and approve one authoritative agency source before proposing live use.'],
  }),
  'radio-browser': access({
    domain: 'radio',
    productId: 'radio-browser-directory',
    productName: 'Radio Browser station directory',
    endpoint: 'https://api.radio-browser.info/',
    format: 'JSON directory',
    coverage: 'Global community-contributed directory; stream rights remain source-specific',
    timeSemantics: 'Directory retrieval is distinct from originating stream time',
    credentialKind: 'none',
    setupUrl: 'https://api.radio-browser.info/',
    validation: 'No directory API key; each originating stream remains separately governed',
    approval: 'record_required',
    termsUrl: 'https://www.radio-browser.info/',
    attributionUrl: 'https://www.radio-browser.info/',
    configuration: 'required',
    configurationDescription:
      'Originating stream rights and proxy configuration are source-specific.',
    refreshSeconds: 60,
    maxStaleSeconds: 300,
    rate: 'Directory and stream requests use their existing bounded proxy paths',
    budget: 'Stream and directory access remain cached, rate limited, and budget governed',
    maxBytes: 5_242_880,
    maxRecords: 5_000,
    killSwitch: 'No dedicated provider kill switch is registered',
    fallback: 'Use the deterministic seed directory or report unavailable',
    instructions: ['Review directory use and each originating stream right separately.'],
  }),
  'launch-replays': access({
    domain: 'launches',
    productId: 'launch-library-replay',
    productName: 'Reconstructed launch trajectory replay',
    endpoint: 'https://ll.thespacedevs.com/2.3.0/launch/',
    format: 'Reconstructed seed JSON',
    coverage: 'Checked-in deterministic launch replay examples',
    timeSemantics: 'Historical event and replay simulation times are never labeled current',
    credentialKind: 'none',
    setupUrl: 'https://ll.thespacedevs.com/docs/',
    validation: 'Live use and optional supporter credentials are not implemented',
    approval: 'record_required',
    termsUrl: 'https://thespacedevs.com/llapi',
    attributionUrl: 'https://thespacedevs.com/',
    configuration: 'required',
    configurationDescription: 'Live source selection, quota, and fixture rights remain unapproved.',
    refreshSeconds: 600,
    maxStaleSeconds: 3_600,
    rate: 'Seed-only; no upstream request is authorized',
    budget: 'Zero live source spend in the current implementation',
    maxBytes: 5_242_880,
    maxRecords: 1_000,
    killSwitch: 'No dedicated provider kill switch is registered',
    fallback: 'Retain the labeled deterministic replay fixture',
    instructions: [
      'Review Launch Library quota, terms, attribution, and fixture rights before live work.',
    ],
  }),
  rainviewer: access({
    domain: 'weather',
    productId: 'rainviewer-seed-weather',
    productName: 'Weather and radar seed observations',
    endpoint: 'https://api.rainviewer.com/public/weather-maps.json',
    format: 'Seed GeoJSON',
    coverage: 'Checked-in deterministic weather station examples',
    timeSemantics: 'Observation, radar frame, and retrieval times remain distinct',
    credentialKind: 'none',
    setupUrl: 'https://www.rainviewer.com/api.html',
    validation: 'No public API key; commercial deployment remains locked by current terms',
    approval: 'record_required',
    termsUrl: 'https://www.rainviewer.com/api.html',
    attributionUrl: 'https://www.rainviewer.com/',
    configuration: 'required',
    configurationDescription:
      'Commercial live rights and a current history/rate policy are absent.',
    refreshSeconds: 300,
    maxStaleSeconds: 1_800,
    rate: 'Seed-only under the current implementation',
    budget: 'Zero live source spend in the current implementation',
    maxBytes: 5_242_880,
    maxRecords: 1_000,
    killSwitch: 'No dedicated provider kill switch is registered',
    fallback: 'Use the labeled deterministic seed fixture or report unavailable',
    instructions: ['Review the current RainViewer public API terms before any live proposal.'],
  }),
  gbfs: access({
    domain: 'mobility',
    productId: 'regional-gbfs',
    productName: 'Regional GBFS station information and status',
    endpoint: 'https://gbfs.org/documentation/reference/',
    format: 'GBFS JSON',
    coverage: 'One separately configured regional GBFS system',
    timeSemantics: 'Feed last_updated and station status remain distinct from retrieval',
    credentialKind: 'source_specific',
    setupUrl: 'https://gbfs.org/documentation/reference/',
    validation: 'Validate the selected feed URL, version, geography, and license fields',
    approval: 'record_required',
    termsUrl: 'https://gbfs.org/documentation/reference/',
    attributionUrl: 'https://gbfs.org/',
    configuration: 'required',
    configurationDescription:
      'Each regional feed URL, license, attribution, and geography is separate.',
    refreshSeconds: 30,
    maxStaleSeconds: 300,
    rate: 'Respect each operator feed cadence through the shared cache',
    budget: 'Each configured operator source requires rate, cache, and budget policy',
    maxBytes: 5_242_880,
    maxRecords: 10_000,
    killSwitch: 'No dedicated provider kill switch is registered',
    fallback: 'Use the deterministic seed fixture or report unavailable',
    instructions: [
      'Select one regional system and review its license, attribution, version, and geography.',
    ],
  }),
  'overpass-api': access({
    domain: 'openstreetmap',
    productId: 'bounded-overpass-query',
    productName: 'Sanitized bounded Overpass query',
    endpoint: 'https://overpass-api.de/api/interpreter',
    format: 'Overpass JSON',
    coverage: 'Caller AOI after sanitizer and endpoint policy bounds',
    timeSemantics: 'OSM element timestamp and retrieval/cache time remain distinct',
    credentialKind: 'none',
    setupUrl: 'https://wiki.openstreetmap.org/wiki/Overpass_API',
    validation: 'No generic key; endpoint policy and sanitizer remain mandatory',
    approval: 'record_required',
    termsUrl: 'https://www.openstreetmap.org/copyright',
    attributionUrl: 'https://www.openstreetmap.org/copyright',
    configuration: 'required',
    configurationDescription:
      'OQ-5 output classification and production endpoint capacity remain open.',
    refreshSeconds: 30,
    maxStaleSeconds: 300,
    rate: 'Public-service capacity policy and bounded query limits apply',
    budget: 'All requests stay sanitized, cached, rate limited, and budget governed',
    maxBytes: 5_242_880,
    maxRecords: 10_000,
    killSwitch: 'No dedicated provider kill switch is registered',
    fallback: 'Keep the visual layer incomplete and report the query feed truthfully',
    instructions: [
      'Resolve OQ-5 and approve one endpoint policy before completing the visual layer.',
    ],
  }),
  'submarine-cables': access({
    domain: 'infrastructure',
    productId: 'licensed-cable-pack',
    productName: 'Synthetic seed or operator-licensed cable pack',
    endpoint: 'https://www2.telegeography.com/license-geocoded-map-data',
    format: 'Validated bounded GeoJSON pack',
    coverage: 'Synthetic global examples or the exact licensed pack manifest',
    timeSemantics: 'Pack vintage, retrieval, verification, and activation times remain distinct',
    credentialKind: 'operator_licensed_manifest',
    setupUrl: 'https://www2.telegeography.com/license-geocoded-map-data',
    validation: 'Manifest, license evidence, allowlisted URL, size, and SHA-256 are mandatory',
    approval: 'record_required',
    termsUrl: 'https://www2.telegeography.com/license-geocoded-map-data',
    attributionUrl: 'https://www.telegeography.com/',
    configuration: 'required',
    configurationDescription: 'Licensed-pack activation requires an approved local manifest.',
    refreshSeconds: 86_400,
    maxStaleSeconds: 604_800,
    rate: 'One bounded verified download-pack activation path',
    budget: 'Activation remains authenticated, audited, approved, and budget governed',
    maxBytes: 52_428_800,
    maxRecords: 10_000,
    killSwitch: 'GEV_CABLES_ENABLED',
    fallback: 'Use the clearly labeled GEV synthetic cable fixture',
    instructions: [
      'Obtain a license for the exact cable dataset and retain its evidence.',
      'Configure the approved manifest and mandatory SHA-256 through the existing operator workflow.',
    ],
    transport: 'download_pack',
  }),
};

export function getBaseProviderAccess(providerId: string): ProviderSourceAccess {
  const decision = BASE_PROVIDER_ACCESS[providerId];
  if (!decision) throw new Error(`Provider '${providerId}' is missing registry access metadata`);
  return decision;
}
