import {
  type ProviderHealth,
  type ProviderRegistry,
  type ProviderRegistryCounts,
  ProviderRegistryCountsSchema,
  type ProviderRegistryFeedView,
  ProviderRegistryFeedViewSchema,
  type ProviderRegistryProvider,
  ProviderRegistrySchema,
  type ProviderRequestedMode,
  type ProviderRuntimeMode,
} from '@gev/contracts';
import { PROVIDER_DEFINITIONS, type ProviderDefinition } from './registryDefinitions.js';

export interface CreateProviderRegistryOptions {
  requestedMode?: ProviderRequestedMode;
  disabledProviderIds?: Iterable<string>;
}

function resolveProviderState(
  definition: ProviderDefinition,
  requestedMode: ProviderRequestedMode,
  disabledProviderIds: ReadonlySet<string>
): { mode: ProviderRuntimeMode; health: ProviderHealth } {
  if (definition.implementation === 'planned') {
    return { mode: 'unavailable', health: 'unavailable' };
  }

  if (definition.implementation === 'incomplete') {
    return {
      mode: definition.supported_modes.includes('download_pack') ? 'download_pack' : 'unavailable',
      health: 'unavailable',
    };
  }

  if (!definition.supported_modes.includes(requestedMode)) {
    return { mode: 'unavailable', health: 'unavailable' };
  }

  return {
    mode: requestedMode,
    health: disabledProviderIds.has(definition.id) ? 'degraded' : 'healthy',
  };
}

export function resolveProviderRequestedMode(
  environment: Readonly<Record<string, string | undefined>> = process.env
): ProviderRequestedMode {
  return environment.GEV_LIVE_MODE === '1' && environment.GEV_SEED_MODE !== '1' ? 'live' : 'seed';
}

export function createProviderRegistry(
  options: CreateProviderRegistryOptions = {}
): ProviderRegistry {
  const requestedMode = options.requestedMode ?? 'seed';
  const disabledProviderIds = new Set(options.disabledProviderIds ?? []);

  return ProviderRegistrySchema.parse({
    version: 2,
    requested_mode: requestedMode,
    providers: PROVIDER_DEFINITIONS.map((definition): ProviderRegistryProvider => {
      const state = resolveProviderState(definition, requestedMode, disabledProviderIds);
      return {
        ...definition,
        ...state,
      };
    }),
  });
}

export function createConfiguredProviderRegistry(
  environment: Readonly<Record<string, string | undefined>> = process.env
): ProviderRegistry {
  return createProviderRegistry({ requestedMode: resolveProviderRequestedMode(environment) });
}

export function summarizeProviderRegistry(registry: ProviderRegistry): ProviderRegistryCounts {
  const providers = registry.providers;
  const activeProviders = providers.filter(
    (provider) => provider.implementation === 'implemented' && provider.health !== 'unavailable'
  );
  const feeds = providers.flatMap((provider) => provider.feeds.map((feed) => ({ provider, feed })));
  const layers = providers.flatMap((provider) =>
    provider.layers.map((layer) => ({ provider, layer }))
  );

  return ProviderRegistryCountsSchema.parse({
    providers: {
      total: providers.length,
      active: activeProviders.length,
    },
    feeds: {
      total: feeds.length,
      active: feeds.filter(
        ({ provider, feed }) =>
          provider.health !== 'unavailable' && feed.implementation === 'implemented'
      ).length,
    },
    layers: {
      total: layers.length,
      active: layers.filter(
        ({ provider, layer }) =>
          provider.health !== 'unavailable' && layer.implementation === 'implemented'
      ).length,
    },
  });
}

export function listProviderRegistryFeeds(registry: ProviderRegistry): ProviderRegistryFeedView[] {
  return registry.providers.flatMap((provider) =>
    provider.feeds.map((feed) =>
      ProviderRegistryFeedViewSchema.parse({
        id: feed.id,
        name: feed.name,
        provider: provider.id,
        provider_name: provider.name,
        source: provider.source,
        implementation: feed.implementation,
        freshness: feed.freshness,
        mode: provider.mode,
        status: feed.implementation === 'implemented' ? provider.health : 'unavailable',
        layer_ids: provider.layers.map((layer) => layer.id),
      })
    )
  );
}

export function withDisabledProviders(
  registry: ProviderRegistry,
  disabledProviderIds: Iterable<string>
): ProviderRegistry {
  const disabled = new Set(disabledProviderIds);
  return ProviderRegistrySchema.parse({
    ...registry,
    providers: registry.providers.map((provider) => ({
      ...provider,
      health:
        disabled.has(provider.id) && provider.health === 'healthy'
          ? ('degraded' as const)
          : provider.health,
    })),
  });
}

export function renderProviderRegistryMarkdown(registry: ProviderRegistry): string {
  const counts = summarizeProviderRegistry(registry);
  const lines = [
    '# Generated Provider Registry',
    '',
    '<!-- Generated by `pnpm docs:providers` from the typed provider registry. -->',
    '',
    `Registry version ${registry.version}; requested mode \`${registry.requested_mode}\`.`,
    '',
    `Active/registered: ${counts.providers.active}/${counts.providers.total} providers, ${counts.feeds.active}/${counts.feeds.total} feeds, ${counts.layers.active}/${counts.layers.total} layers.`,
    '',
    '| Provider | Feed | Layer | Source | License ID | License / terms | Attribution | Freshness | Provider state | Feed state | Layer state | Mode | Health | Documentation |',
    '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|',
  ];

  for (const provider of registry.providers) {
    const feed = provider.feeds[0];
    const layer = provider.layers[0];
    if (!feed || !layer) {
      continue;
    }
    const docsLink = `../${layer.documentation_path.replace(/^docs\//, '')}`;
    const freshness =
      feed.freshness.status === 'defined'
        ? `${feed.freshness.fresh_for_seconds}s`
        : `unavailable: ${feed.freshness.reason}`;
    lines.push(
      `| \`${provider.id}\` | \`${feed.id}\` | \`${layer.id}\` | [${provider.source.name}](${provider.source.url}) | \`${provider.source.license_id}\` | ${provider.source.license} | ${provider.source.attribution} | ${freshness} | ${provider.implementation} | ${feed.implementation} | ${layer.implementation} | ${provider.mode} | ${provider.health} | [${layer.name}](${docsLink}) |`
    );
  }

  lines.push(
    '',
    'Entries marked `planned`, `incomplete`, `download_pack`, or `unavailable` are registered for truthful discovery and are not counted as active.',
    '',
    'Implemented provider responses carry DataProvenance schema version 1. Freshness is observation age evaluated against the registry threshold; cache retention is a separate server policy.',
    '',
    'License and attribution details are source-specific; see each linked data-source document before enabling live or redistributed data.',
    ''
  );

  return lines.join('\n');
}
